name: Docker Image CI

on:
  push:
    branches: ['main']

env:
  # docker hub의 organization 이름
  REGISTRY: eatcocoa
  # build and push 할 docker image 이름
  IMAGE_NAME: unknown-contract-backend
  # build and push 할 docker image의 tag
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # tonistiigi/binfmt 이미지를 이용해 qemu 설치
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      # docker buildx 설치
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          platforms: |
            linux/arm64
            linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
